// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD73JABA7ORcq61iqQNCiCPsXhGbZUQQ9A',
    appId: '1:725574038389:web:3f57746b43fb2d2c7d193c',
    messagingSenderId: '725574038389',
    projectId: 'zaad-e8589',
    authDomain: 'zaad-e8589.firebaseapp.com',
    storageBucket: 'zaad-e8589.firebasestorage.app',
    measurementId: 'G-2FNVF0NSH4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBip9763svPsQ9OMM_WMI4ddbfSd2Nzh8A',
    appId: '1:725574038389:android:f5744328928667657d193c',
    messagingSenderId: '725574038389',
    projectId: 'zaad-e8589',
    storageBucket: 'zaad-e8589.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBe2mMDIrxVOF2_JWazeeomGcCnHBknYoA',
    appId: '1:725574038389:ios:af5f1b8023e5c1c87d193c',
    messagingSenderId: '725574038389',
    projectId: 'zaad-e8589',
    storageBucket: 'zaad-e8589.firebasestorage.app',
    iosBundleId: 'com.example.posApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBe2mMDIrxVOF2_JWazeeomGcCnHBknYoA',
    appId: '1:725574038389:ios:af5f1b8023e5c1c87d193c',
    messagingSenderId: '725574038389',
    projectId: 'zaad-e8589',
    storageBucket: 'zaad-e8589.firebasestorage.app',
    iosBundleId: 'com.example.posApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD73JABA7ORcq61iqQNCiCPsXhGbZUQQ9A',
    appId: '1:725574038389:web:c5ca2e31cc587d517d193c',
    messagingSenderId: '725574038389',
    projectId: 'zaad-e8589',
    authDomain: 'zaad-e8589.firebaseapp.com',
    storageBucket: 'zaad-e8589.firebasestorage.app',
    measurementId: 'G-X13JWCGXTR',
  );
}
